# This file is generated by hopsworks-apigen.
# Do not edit it manually!
# It is managed by hopsworks-apigen and is subject to periodical deletion.
import hopsworks_common.client


_is_external = hopsworks_common.client._is_external
get_connection = hopsworks_common.client.get_connection
get_instance = hopsworks_common.client.get_instance
get_knative_domain = hopsworks_common.client.get_knative_domain
get_serving_num_instances_limits = (
    hopsworks_common.client.get_serving_num_instances_limits
)
init = hopsworks_common.client.init
is_kserve_installed = hopsworks_common.client.is_kserve_installed
is_saas_connection = hopsworks_common.client.is_saas_connection
is_scale_to_zero_required = hopsworks_common.client.is_scale_to_zero_required
set_connection = hopsworks_common.client.set_connection
set_knative_domain = hopsworks_common.client.set_knative_domain
set_kserve_installed = hopsworks_common.client.set_kserve_installed
set_serving_num_instances_limits = (
    hopsworks_common.client.set_serving_num_instances_limits
)
stop = hopsworks_common.client.stop
