# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client
_client = hopsworks.internal.platform.client._client
_connection = hopsworks.internal.platform.client._connection
_is_external = hopsworks.internal.platform.client._is_external
_knative_domain = hopsworks.internal.platform.client._knative_domain
_kserve_installed = hopsworks.internal.platform.client._kserve_installed
_serving_num_instances_limits = hopsworks.internal.platform.client._serving_num_instances_limits
get_connection = hopsworks.internal.platform.client.get_connection
get_instance = hopsworks.internal.platform.client.get_instance
get_knative_domain = hopsworks.internal.platform.client.get_knative_domain
get_serving_num_instances_limits = hopsworks.internal.platform.client.get_serving_num_instances_limits
init = hopsworks.internal.platform.client.init
is_kserve_installed = hopsworks.internal.platform.client.is_kserve_installed
is_saas_connection = hopsworks.internal.platform.client.is_saas_connection
is_scale_to_zero_required = hopsworks.internal.platform.client.is_scale_to_zero_required
online_store_rest_client = hopsworks.internal.platform.client.online_store_rest_client
set_connection = hopsworks.internal.platform.client.set_connection
set_knative_domain = hopsworks.internal.platform.client.set_knative_domain
set_kserve_installed = hopsworks.internal.platform.client.set_kserve_installed
set_serving_num_instances_limits = hopsworks.internal.platform.client.set_serving_num_instances_limits
stop = hopsworks.internal.platform.client.stop
