# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.utils.schema.tensor_schema
TensorSchema = hopsworks.internal.ml.utils.schema.tensor_schema.TensorSchema
