# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.constructor.filter
Filter = hopsworks.internal.fs.constructor.filter.Filter
Logic = hopsworks.internal.fs.constructor.filter.Logic
