# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.core.explicit_provenance
Artifact = hopsworks.internal.ml.core.explicit_provenance.Artifact
Links = hopsworks.internal.ml.core.explicit_provenance.Links
ProvenanceEncoder = hopsworks.internal.ml.core.explicit_provenance.ProvenanceEncoder
