# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.resources
ComponentResources = hopsworks.internal.ml.resources.ComponentResources
PredictorResources = hopsworks.internal.ml.resources.PredictorResources
Resources = hopsworks.internal.ml.resources.Resources
TransformerResources = hopsworks.internal.ml.resources.TransformerResources
