# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.core.model_serving_api
ModelServingApi = hopsworks.internal.ml.core.model_serving_api.ModelServingApi
