#
#   Copyright 2026 Hopsworks AB
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Every WINDOWED statement the backend can emit for an inference spine, bound against Spark.

The golden file is generated by hopsworks-ee (`TestSpineSqlGenerator#testGoldenSqlForEveryShape`)
and copied here and into flyingduck, which binds the ASOF rendering against DuckDB. The two
renderings diverged the moment one needed an engine function the other lacks: `timestamp_millis`
and `ARRAY<FLOAT>` are Spark, `epoch_ms` and `FLOAT[]` are DuckDB. A rendering that only parses
in the engine it was not written for is exactly what this catches.
"""

from __future__ import annotations

import pathlib
import sys

import pandas as pd
import pytest


SHAPES_FILE = (
    pathlib.Path(__file__).parent.parent
    / "resources"
    / "spine"
    / "spine_sql_shapes.sql"
)


def _statements():
    label, buffer, out = None, [], []
    for line in SHAPES_FILE.read_text().splitlines():
        if line.startswith("-- "):
            if label and buffer:
                out.append((label, "\n".join(buffer).strip().rstrip(";")))
            label, buffer = line[3:].strip(), []
        elif line.strip():
            buffer.append(line)
    if label and buffer:
        out.append((label, "\n".join(buffer).strip().rstrip(";")))
    return out


STATEMENTS = _statements()
WINDOWED = [(label, sql) for label, sql in STATEMENTS if label.startswith("WINDOWED ")]


@pytest.fixture(scope="module")
def spark():
    pytest.importorskip("pyspark")
    if sys.platform == "win32":
        # The shapes reference `<featurestore>.<table>`, so binding them needs a database and
        # tables, and Spark's catalog reaches Hadoop's file operations for those. On Windows that
        # needs winutils.exe, which CI does not install. The same golden file is bound on Linux
        # here and against DuckDB in flyingduck, so nothing goes unchecked.
        pytest.skip("Spark's catalog needs winutils.exe on Windows")
    pandas_version = tuple(int(p) for p in pd.__version__.split(".")[:2])
    if pandas_version < (2, 2):
        pytest.skip(f"pyspark needs pandas >= 2.2; have {pd.__version__}")
    from pyspark.sql import SparkSession

    session = (
        SparkSession.builder.master("local[1]")
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.ui.enabled", "false")
        .getOrCreate()
    )
    # Spark has no schemas to CREATE, so the `<featurestore>.<table>` references resolve through
    # a database of that name holding empty tables of the golden shapes' columns.
    session.sql("CREATE DATABASE IF NOT EXISTS test_proj_featurestore")
    tables = {
        "test_proj_featurestore.air_quality_1": "country STRING, city STRING, street STRING,"
        " date TIMESTAMP, pm25 DOUBLE",
        "test_proj_featurestore.weather_1": "city STRING, station STRING, date TIMESTAMP,"
        " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE",
        "test_proj_featurestore.air_quality_epoch_1": "country STRING, city STRING,"
        " street STRING, date BIGINT, pm25 DOUBLE",
        "test_proj_featurestore.weather_epoch_1": "city STRING, date BIGINT,"
        " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE",
    }
    for name, columns in tables.items():
        session.sql(f"CREATE TABLE IF NOT EXISTS {name} ({columns}) USING parquet")
    session.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_3f9a AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(1.0 AS DOUBLE))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date, label) WHERE 1 = 0"
    )
    session.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_e90c AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen', CAST(1789516800000 AS BIGINT))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date) WHERE 1 = 0"
    )
    yield session
    for name in tables:
        session.sql(f"DROP TABLE IF EXISTS {name}")
    session.sql("DROP DATABASE IF EXISTS test_proj_featurestore")


def test_the_golden_file_is_the_same_one_the_backend_generates():
    labels = [label for label, _ in STATEMENTS]
    windowed = {
        label[len("WINDOWED ") :] for label in labels if label.startswith("WINDOWED ")
    }
    asof = {label[len("ASOF ") :] for label in labels if label.startswith("ASOF ")}
    assert asof == windowed
    assert len(windowed) >= 18, (
        "shapes were removed from the golden file rather than added"
    )


def _statement(label):
    return next(sql for name, sql in STATEMENTS if name == label)


def test_a_declared_default_fills_a_matched_null_and_nothing_else(spark):
    """The Spark rendering must agree with the DuckDB one, which flyingduck asserts the same way.

    The two apply the feature-age bound in different places, so the guard that decides whether a
    default applies has to be the lookup's event time rather than the value being NULL.
    """
    spark.sql(
        "CREATE OR REPLACE TEMP VIEW weather_rows AS SELECT * FROM VALUES"
        " ('Stockholm', 'arlanda', TIMESTAMP '2026-09-13 00:00:00', CAST(NULL AS DOUBLE),"
        " CAST(3.0 AS DOUBLE))"
        " AS t(city, station, date, temperature_2m_mean, wind_speed_10m_max)"
    )
    spark.sql("DROP TABLE IF EXISTS test_proj_featurestore.weather_1")
    spark.sql(
        "CREATE TABLE test_proj_featurestore.weather_1 USING parquet AS SELECT * FROM weather_rows"
    )
    spark.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_3f9a AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(NULL AS DOUBLE)),"
        " (CAST(1 AS BIGINT), 'SE', 'Gothenburg', 'Avenyn',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(NULL AS DOUBLE))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date, label)"
    )
    try:
        rows = spark.sql(
            _statement("WINDOWED defaulted_feature").replace('"', "`")
        ).collect()
        temperature = [row["temperature_2m_mean"] for row in rows]
        assert temperature == [42.0, None], (
            "a matched row holding NULL takes the declared default, a spine row that matched"
            f" nothing stays NULL; got {temperature}"
        )
    finally:
        spark.sql("DROP TABLE IF EXISTS test_proj_featurestore.weather_1")
        spark.sql(
            "CREATE TABLE test_proj_featurestore.weather_1"
            " (city STRING, station STRING, date TIMESTAMP,"
            " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE) USING parquet"
        )


def test_an_empty_string_default_is_a_default(spark):
    """An empty string is a declared default, not the absence of one.

    The spine generator treated it as absent, so a matched row holding NULL trained as NULL while
    the online statement answered with the empty string. DuckDB asserts the same two rows.
    """
    spark.sql(
        "CREATE OR REPLACE TEMP VIEW station_rows AS SELECT * FROM VALUES"
        " ('Stockholm', TIMESTAMP '2026-09-13 00:00:00', CAST(NULL AS STRING))"
        " AS t(city, date, station)"
    )
    spark.sql("DROP TABLE IF EXISTS test_proj_featurestore.weather_1")
    spark.sql(
        "CREATE TABLE test_proj_featurestore.weather_1 USING parquet AS SELECT * FROM station_rows"
    )
    spark.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_3f9a AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(NULL AS DOUBLE)),"
        " (CAST(1 AS BIGINT), 'SE', 'Gothenburg', 'Avenyn',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(NULL AS DOUBLE))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date, label)"
    )
    try:
        rows = spark.sql(
            _statement("WINDOWED empty_string_default").replace('"', "`")
        ).collect()
        station = [row["station"] for row in rows]
        assert station == ["", None], (
            "a matched row holding NULL takes the empty-string default, a spine row that matched"
            f" nothing stays NULL; got {station}"
        )
    finally:
        spark.sql("DROP TABLE IF EXISTS test_proj_featurestore.weather_1")
        spark.sql(
            "CREATE TABLE test_proj_featurestore.weather_1"
            " (city STRING, station STRING, date TIMESTAMP,"
            " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE) USING parquet"
        )


@pytest.mark.parametrize("label, sql", WINDOWED, ids=[label for label, _ in WINDOWED])
def test_shape_binds_in_spark(spark, label, sql):
    # Analysed without being executed: the tables are empty, and what is under test is whether
    # the statement parses and every identifier and function in it resolves. The golden file
    # spells identifiers with double quotes for readability; what the backend emits is backticks,
    # which is what Spark quotes identifiers with.
    schema = spark.sql(sql.replace('"', "`")).schema
    assert len(schema.fields) > 0
