#
#   Copyright 2026 Hopsworks AB
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Every WINDOWED statement the backend can emit for an inference spine, bound against Spark.

The golden file is generated by hopsworks-ee (`TestSpineSqlGenerator#testGoldenSqlForEveryShape`)
and copied here and into flyingduck, which binds the ASOF rendering against DuckDB. The two
renderings diverged the moment one needed an engine function the other lacks: `timestamp_millis`
and `ARRAY<FLOAT>` are Spark, `epoch_ms` and `FLOAT[]` are DuckDB. A rendering that only parses
in the engine it was not written for is exactly what this catches.
"""

from __future__ import annotations

import pathlib

import pandas as pd
import pytest


SHAPES_FILE = (
    pathlib.Path(__file__).parent.parent
    / "resources"
    / "spine"
    / "spine_sql_shapes.sql"
)


def _statements():
    label, buffer, out = None, [], []
    for line in SHAPES_FILE.read_text().splitlines():
        if line.startswith("-- "):
            if label and buffer:
                out.append((label, "\n".join(buffer).strip().rstrip(";")))
            label, buffer = line[3:].strip(), []
        elif line.strip():
            buffer.append(line)
    if label and buffer:
        out.append((label, "\n".join(buffer).strip().rstrip(";")))
    return out


STATEMENTS = _statements()
WINDOWED = [(label, sql) for label, sql in STATEMENTS if label.startswith("WINDOWED ")]


@pytest.fixture(scope="module")
def spark():
    pytest.importorskip("pyspark")
    pandas_version = tuple(int(p) for p in pd.__version__.split(".")[:2])
    if pandas_version < (2, 2):
        pytest.skip(f"pyspark needs pandas >= 2.2; have {pd.__version__}")
    from pyspark.sql import SparkSession

    session = (
        SparkSession.builder.master("local[1]")
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.ui.enabled", "false")
        .getOrCreate()
    )
    # Spark has no schemas to CREATE, so the `<featurestore>.<table>` references resolve through
    # a database of that name holding empty tables of the golden shapes' columns.
    session.sql("CREATE DATABASE IF NOT EXISTS test_proj_featurestore")
    tables = {
        "test_proj_featurestore.air_quality_1": "country STRING, city STRING, street STRING,"
        " date TIMESTAMP, pm25 DOUBLE",
        "test_proj_featurestore.weather_1": "city STRING, station STRING, date TIMESTAMP,"
        " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE",
        "test_proj_featurestore.air_quality_epoch_1": "country STRING, city STRING,"
        " street STRING, date BIGINT, pm25 DOUBLE",
        "test_proj_featurestore.weather_epoch_1": "city STRING, date BIGINT,"
        " temperature_2m_mean DOUBLE, wind_speed_10m_max DOUBLE",
    }
    for name, columns in tables.items():
        session.sql(f"CREATE TABLE IF NOT EXISTS {name} ({columns}) USING parquet")
    session.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_3f9a AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen',"
        " TIMESTAMP '2026-09-14 08:00:00', CAST(1.0 AS DOUBLE))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date, label) WHERE 1 = 0"
    )
    session.sql(
        "CREATE OR REPLACE TEMP VIEW __hopsworks_spine_e90c AS SELECT * FROM VALUES"
        " (CAST(0 AS BIGINT), 'SE', 'Stockholm', 'Sveavagen', CAST(1789516800000 AS BIGINT))"
        " AS t(__hopsworks_spine_row_id, country, city, street, date) WHERE 1 = 0"
    )
    yield session
    for name in tables:
        session.sql(f"DROP TABLE IF EXISTS {name}")
    session.sql("DROP DATABASE IF EXISTS test_proj_featurestore")


def test_the_golden_file_is_the_same_one_the_backend_generates():
    labels = [label for label, _ in STATEMENTS]
    windowed = {
        label[len("WINDOWED ") :] for label in labels if label.startswith("WINDOWED ")
    }
    asof = {label[len("ASOF ") :] for label in labels if label.startswith("ASOF ")}
    assert asof == windowed
    assert len(windowed) >= 14, (
        "shapes were removed from the golden file rather than added"
    )


@pytest.mark.parametrize("label, sql", WINDOWED, ids=[label for label, _ in WINDOWED])
def test_shape_binds_in_spark(spark, label, sql):
    # Analysed without being executed: the tables are empty, and what is under test is whether
    # the statement parses and every identifier and function in it resolves. The golden file
    # spells identifiers with double quotes for readability; what the backend emits is backticks,
    # which is what Spark quotes identifiers with.
    schema = spark.sql(sql.replace('"', "`")).schema
    assert len(schema.fields) > 0
