# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.feature_monitoring_config
FeatureMonitoringConfig = hopsworks.internal.fs.core.feature_monitoring_config.FeatureMonitoringConfig
FeatureMonitoringType = hopsworks.internal.fs.core.feature_monitoring_config.FeatureMonitoringType
MAX_LENGTH_DESCRIPTION = hopsworks.internal.fs.core.feature_monitoring_config.MAX_LENGTH_DESCRIPTION
