# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.online_ingestion_api
OnlineIngestionApi = hopsworks.internal.fs.core.online_ingestion_api.OnlineIngestionApi
