# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.online_store_rest_client
OnlineStoreRestClientSingleton = hopsworks.internal.platform.client.online_store_rest_client.OnlineStoreRestClientSingleton
get_instance = hopsworks.internal.platform.client.online_store_rest_client.get_instance
init_or_reset_online_store_rest_client = hopsworks.internal.platform.client.online_store_rest_client.init_or_reset_online_store_rest_client
