# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.engine.spark
Engine = hopsworks.internal.fs.engine.spark.Engine
SchemaError = hopsworks.internal.fs.engine.spark.SchemaError
