# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.validation_report_api
ValidationReportApi = hopsworks.internal.fs.core.validation_report_api.ValidationReportApi
