# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.embedding
EmbeddingFeature = hopsworks.internal.fs.embedding.EmbeddingFeature
EmbeddingIndex = hopsworks.internal.fs.embedding.EmbeddingIndex
HsmlModel = hopsworks.internal.fs.embedding.HsmlModel
SimilarityFunctionType = hopsworks.internal.fs.embedding.SimilarityFunctionType
