# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.inference_endpoint
InferenceEndpoint = hopsworks.internal.ml.inference_endpoint.InferenceEndpoint
InferenceEndpointPort = hopsworks.internal.ml.inference_endpoint.InferenceEndpointPort
get_endpoint_by_type = hopsworks.internal.ml.inference_endpoint.get_endpoint_by_type
