# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.engine
_engine = hopsworks.internal.fs.engine._engine
_engine_type = hopsworks.internal.fs.engine._engine_type
get_instance = hopsworks.internal.fs.engine.get_instance
get_type = hopsworks.internal.fs.engine.get_type
init = hopsworks.internal.fs.engine.init
set_instance = hopsworks.internal.fs.engine.set_instance
stop = hopsworks.internal.fs.engine.stop
