# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.opensearch_api
OPENSEARCH_CONFIG = hopsworks.internal.platform.core.opensearch_api.OPENSEARCH_CONFIG
OpenSearchApi = hopsworks.internal.platform.core.opensearch_api.OpenSearchApi
