# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.constructor.external_feature_group_alias
ExternalFeatureGroupAlias = hopsworks.internal.fs.constructor.external_feature_group_alias.ExternalFeatureGroupAlias
