# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.constructor.serving_prepared_statement
ServingPreparedStatement = hopsworks.internal.fs.constructor.serving_prepared_statement.ServingPreparedStatement
