# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.feature_group
ExternalFeatureGroup = hopsworks.internal.fs.feature_group.ExternalFeatureGroup
FeatureGroup = hopsworks.internal.fs.feature_group.FeatureGroup
FeatureGroupBase = hopsworks.internal.fs.feature_group.FeatureGroupBase
SpineGroup = hopsworks.internal.fs.feature_group.SpineGroup
