# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.feature_store
FeatureStore = hopsworks.internal.fs.feature_store.FeatureStore
