# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.connection
CERT_FOLDER_DEFAULT = hopsworks.internal.platform.connection.CERT_FOLDER_DEFAULT
Connection = hopsworks.internal.platform.connection.Connection
HOPSWORKS_HOSTNAME_VERIFICATION_DEFAULT = hopsworks.internal.platform.connection.HOPSWORKS_HOSTNAME_VERIFICATION_DEFAULT
HOPSWORKS_PORT_DEFAULT = hopsworks.internal.platform.connection.HOPSWORKS_PORT_DEFAULT
HOSTNAME_VERIFICATION_DEFAULT = hopsworks.internal.platform.connection.HOSTNAME_VERIFICATION_DEFAULT
PROJECT_ID = hopsworks.internal.platform.connection.PROJECT_ID
PROJECT_NAME = hopsworks.internal.platform.connection.PROJECT_NAME
_hsfs_engine_type = hopsworks.internal.platform.connection._hsfs_engine_type
_logger = hopsworks.internal.platform.connection._logger
