# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.istio.hopsworks
Client = hopsworks.internal.platform.client.istio.hopsworks.Client
