# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.exceptions
DataValidationException = hopsworks.internal.platform.client.exceptions.DataValidationException
DatasetException = hopsworks.internal.platform.client.exceptions.DatasetException
EnvironmentException = hopsworks.internal.platform.client.exceptions.EnvironmentException
ExternalClientError = hopsworks.internal.platform.client.exceptions.ExternalClientError
FeatureStoreException = hopsworks.internal.platform.client.exceptions.FeatureStoreException
GitException = hopsworks.internal.platform.client.exceptions.GitException
HopsworksSSLClientError = hopsworks.internal.platform.client.exceptions.HopsworksSSLClientError
InternalClientError = hopsworks.internal.platform.client.exceptions.InternalClientError
JobException = hopsworks.internal.platform.client.exceptions.JobException
JobExecutionException = hopsworks.internal.platform.client.exceptions.JobExecutionException
KafkaException = hopsworks.internal.platform.client.exceptions.KafkaException
ModelRegistryException = hopsworks.internal.platform.client.exceptions.ModelRegistryException
ModelServingException = hopsworks.internal.platform.client.exceptions.ModelServingException
OpenSearchException = hopsworks.internal.platform.client.exceptions.OpenSearchException
ProjectException = hopsworks.internal.platform.client.exceptions.ProjectException
RestAPIError = hopsworks.internal.platform.client.exceptions.RestAPIError
UnknownSecretStorageError = hopsworks.internal.platform.client.exceptions.UnknownSecretStorageError
VectorDatabaseException = hopsworks.internal.platform.client.exceptions.VectorDatabaseException
