# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.constructor.prepared_statement_parameter
PreparedStatementParameter = hopsworks.internal.fs.constructor.prepared_statement_parameter.PreparedStatementParameter
