# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.flink_cluster
FlinkCluster = hopsworks.internal.platform.flink_cluster.FlinkCluster
