# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.kafka_topic
KafkaTopic = hopsworks.internal.platform.kafka_topic.KafkaTopic
