# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.job_api
JobApi = hopsworks.internal.platform.core.job_api.JobApi
