# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.expectation_suite
ExpectationSuite = hopsworks.internal.fs.expectation_suite.ExpectationSuite
