# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.feature_view
FeatureView = hopsworks.internal.fs.feature_view.FeatureView
SplineDataFrameTypes = hopsworks.internal.fs.feature_view.SplineDataFrameTypes
TrainingDatasetDataFrameTypes = hopsworks.internal.fs.feature_view.TrainingDatasetDataFrameTypes
pl = hopsworks.internal.fs.feature_view.pl
