# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.feature_store_activity
FeatureStoreActivity = hopsworks.internal.fs.feature_store_activity.FeatureStoreActivity
FeatureStoreActivityType = hopsworks.internal.fs.feature_store_activity.FeatureStoreActivityType
