# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.arrow_flight_client
ArrowFlightClient = hopsworks.internal.fs.core.arrow_flight_client.ArrowFlightClient
_disable_feature_query_service_client = hopsworks.internal.fs.core.arrow_flight_client._disable_feature_query_service_client
_get_connector_options = hopsworks.internal.fs.core.arrow_flight_client._get_connector_options
_is_feature_query_service_queue_full_error = hopsworks.internal.fs.core.arrow_flight_client._is_feature_query_service_queue_full_error
_is_no_commits_found_error = hopsworks.internal.fs.core.arrow_flight_client._is_no_commits_found_error
_is_query_supported_rec = hopsworks.internal.fs.core.arrow_flight_client._is_query_supported_rec
_serialize_feature_name = hopsworks.internal.fs.core.arrow_flight_client._serialize_feature_name
_serialize_featuregroup_connector = hopsworks.internal.fs.core.arrow_flight_client._serialize_featuregroup_connector
_serialize_featuregroup_name = hopsworks.internal.fs.core.arrow_flight_client._serialize_featuregroup_name
_serialize_filter = hopsworks.internal.fs.core.arrow_flight_client._serialize_filter
_serialize_filter_expression = hopsworks.internal.fs.core.arrow_flight_client._serialize_filter_expression
_serialize_filter_or_logic = hopsworks.internal.fs.core.arrow_flight_client._serialize_filter_or_logic
_serialize_logic = hopsworks.internal.fs.core.arrow_flight_client._serialize_logic
_should_retry = hopsworks.internal.fs.core.arrow_flight_client._should_retry
_should_retry_certificate_registration = hopsworks.internal.fs.core.arrow_flight_client._should_retry_certificate_registration
_should_retry_healthcheck = hopsworks.internal.fs.core.arrow_flight_client._should_retry_healthcheck
_translate_to_duckdb = hopsworks.internal.fs.core.arrow_flight_client._translate_to_duckdb
close = hopsworks.internal.fs.core.arrow_flight_client.close
get_instance = hopsworks.internal.fs.core.arrow_flight_client.get_instance
is_data_format_supported = hopsworks.internal.fs.core.arrow_flight_client.is_data_format_supported
is_query_supported = hopsworks.internal.fs.core.arrow_flight_client.is_query_supported
supports = hopsworks.internal.fs.core.arrow_flight_client.supports
