# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.variable_api
LOADBALANCER_SERVICES = hopsworks.internal.platform.core.variable_api.LOADBALANCER_SERVICES
VariableApi = hopsworks.internal.platform.core.variable_api.VariableApi
