# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.feature_store_activity_api
FeatureStoreActivityApi = hopsworks.internal.fs.core.feature_store_activity_api.FeatureStoreActivityApi
