# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.istio
_client = hopsworks.internal.platform.client.istio._client
get_instance = hopsworks.internal.platform.client.istio.get_instance
init = hopsworks.internal.platform.client.istio.init
