# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.ml.deployable_component_logs
DeployableComponentLogs = hopsworks.internal.ml.deployable_component_logs.DeployableComponentLogs
