# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.transformation_function
TransformationFunction = hopsworks.internal.fs.transformation_function.TransformationFunction
TransformationType = hopsworks.internal.fs.transformation_function.TransformationType
