# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.engine.git_engine
GitEngine = hopsworks.internal.platform.engine.git_engine.GitEngine
