# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.monitoring_window_config_engine
MonitoringWindowConfigEngine = hopsworks.internal.fs.core.monitoring_window_config_engine.MonitoringWindowConfigEngine
