# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.opensearch
OpenSearchClientSingleton = hopsworks.internal.platform.core.opensearch.OpenSearchClientSingleton
OpensearchRequestOption = hopsworks.internal.platform.core.opensearch.OpensearchRequestOption
