exclude: setup.py
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/jshwi/docsig
    rev: v0.80.0
    hooks:
      - id: docsig
        files: ^(hopsworks_common|hopsworks|hsfs|hsml)/
        types: [python]
