# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.constants
HAS_AIOMYSQL = hopsworks.internal.platform.core.constants.HAS_AIOMYSQL
HAS_AVRO = hopsworks.internal.platform.core.constants.HAS_AVRO
HAS_CONFLUENT_KAFKA = hopsworks.internal.platform.core.constants.HAS_CONFLUENT_KAFKA
HAS_FAST_AVRO = hopsworks.internal.platform.core.constants.HAS_FAST_AVRO
HAS_GREAT_EXPECTATIONS = hopsworks.internal.platform.core.constants.HAS_GREAT_EXPECTATIONS
HAS_NUMPY = hopsworks.internal.platform.core.constants.HAS_NUMPY
HAS_PANDAS = hopsworks.internal.platform.core.constants.HAS_PANDAS
HAS_POLARS = hopsworks.internal.platform.core.constants.HAS_POLARS
HAS_PYARROW = hopsworks.internal.platform.core.constants.HAS_PYARROW
HAS_SQLALCHEMY = hopsworks.internal.platform.core.constants.HAS_SQLALCHEMY
avro_not_installed_message = hopsworks.internal.platform.core.constants.avro_not_installed_message
confluent_kafka_not_installed_message = hopsworks.internal.platform.core.constants.confluent_kafka_not_installed_message
great_expectations_not_installed_message = hopsworks.internal.platform.core.constants.great_expectations_not_installed_message
initialise_expectation_suite_for_single_expectation_api_message = hopsworks.internal.platform.core.constants.initialise_expectation_suite_for_single_expectation_api_message
numpy_not_installed_message = hopsworks.internal.platform.core.constants.numpy_not_installed_message
polars_not_installed_message = hopsworks.internal.platform.core.constants.polars_not_installed_message
pyarrow_not_installed_message = hopsworks.internal.platform.core.constants.pyarrow_not_installed_message
