# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.execution_api
ExecutionApi = hopsworks.internal.platform.core.execution_api.ExecutionApi
