# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.storage_connector
AdlsConnector = hopsworks.internal.fs.storage_connector.AdlsConnector
BigQueryConnector = hopsworks.internal.fs.storage_connector.BigQueryConnector
GcsConnector = hopsworks.internal.fs.storage_connector.GcsConnector
HopsFSConnector = hopsworks.internal.fs.storage_connector.HopsFSConnector
JdbcConnector = hopsworks.internal.fs.storage_connector.JdbcConnector
KafkaConnector = hopsworks.internal.fs.storage_connector.KafkaConnector
RdsConnector = hopsworks.internal.fs.storage_connector.RdsConnector
RedshiftConnector = hopsworks.internal.fs.storage_connector.RedshiftConnector
S3Connector = hopsworks.internal.fs.storage_connector.S3Connector
SnowflakeConnector = hopsworks.internal.fs.storage_connector.SnowflakeConnector
StorageConnector = hopsworks.internal.fs.storage_connector.StorageConnector
