# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.constants
ARTIFACT_VERSION = hopsworks.internal.platform.constants.ARTIFACT_VERSION
DEFAULT = hopsworks.internal.platform.constants.DEFAULT
DEPLOYABLE_COMPONENT = hopsworks.internal.platform.constants.DEPLOYABLE_COMPONENT
DEPLOYMENT = hopsworks.internal.platform.constants.DEPLOYMENT
Default = hopsworks.internal.platform.constants.Default
ENV_VARS = hopsworks.internal.platform.constants.ENV_VARS
FEATURES = hopsworks.internal.platform.constants.FEATURES
GIT = hopsworks.internal.platform.constants.GIT
HOSTS = hopsworks.internal.platform.constants.HOSTS
INFERENCE_BATCHER = hopsworks.internal.platform.constants.INFERENCE_BATCHER
INFERENCE_ENDPOINTS = hopsworks.internal.platform.constants.INFERENCE_ENDPOINTS
INFERENCE_LOGGER = hopsworks.internal.platform.constants.INFERENCE_LOGGER
JOBS = hopsworks.internal.platform.constants.JOBS
KAFKA_CONSUMER_CONFIG = hopsworks.internal.platform.constants.KAFKA_CONSUMER_CONFIG
KAFKA_PRODUCER_CONFIG = hopsworks.internal.platform.constants.KAFKA_PRODUCER_CONFIG
KAFKA_SSL_CONFIG = hopsworks.internal.platform.constants.KAFKA_SSL_CONFIG
KAFKA_TOPIC = hopsworks.internal.platform.constants.KAFKA_TOPIC
MODEL = hopsworks.internal.platform.constants.MODEL
MODEL_REGISTRY = hopsworks.internal.platform.constants.MODEL_REGISTRY
MODEL_SERVING = hopsworks.internal.platform.constants.MODEL_SERVING
OPENSEARCH_CONFIG = hopsworks.internal.platform.constants.OPENSEARCH_CONFIG
PREDICTOR = hopsworks.internal.platform.constants.PREDICTOR
PREDICTOR_STATE = hopsworks.internal.platform.constants.PREDICTOR_STATE
RESOURCES = hopsworks.internal.platform.constants.RESOURCES
SERVICES = hopsworks.internal.platform.constants.SERVICES
SSL_CONFIG = hopsworks.internal.platform.constants.SSL_CONFIG
