#
#   Copyright 2026 Hopsworks AB
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
from __future__ import annotations

import atexit
import logging
import math
import os
import queue
import shutil
import threading
import time
import uuid
from datetime import datetime, timezone
from typing import Any

import humps
from hopsworks_apigen import public
from hopsworks_common.client.exceptions import (
    FeatureStoreException,
    ModelServingException,
)
from hopsworks_common.constants import MODEL_SERVING
from hopsworks_common.core.feature_logging_buffer import (
    _BufferBudget,
    _positive_env,
    _Reservation,
)
from hsml.deployment.schema import (
    RESERVED_LOGGING_COLUMNS,
    _check_training_dataset_version,
    _encode_value,
    _family,
)


_logger = logging.getLogger(__name__)

STUB_SCRIPT = """# Generated by the hopsworks Python library. Do not edit.
# To customise, subclass hsml.deployment.default_predictor.DefaultPredict in your own
# script and pass it as script_file to deploy() with default_predictor=True.
# The fallback import is for an inference image whose library predates
# hsml.deployment becoming a package: the deployment is created by the client
# and this file then runs against whatever library the image ships.
try:
    from hsml.deployment.default_predictor import DefaultPredict as Predict
except ImportError:
    from hsml.default_predictor import DefaultPredict as Predict

if __name__ == "__main__":
    # A deployment without a model artifact is started by the backend as
    # `python <this file>`. Hand over to the KServe wrapper that model
    # deployments run; it loads the Predict class above from SCRIPT_PATH.
    try:
        from hsml.deployment.default_predictor import run_kserve_wrapper
    except ImportError:
        from hsml.default_predictor import run_kserve_wrapper

    run_kserve_wrapper()
"""

_LAUNCHER = "kserve_server_launcher.sh"
_MODEL_FILE_EXTENSIONS = (".pkl", ".pickle", ".joblib")

_PANDAS_FAMILIES = {
    "int": "integer",
    "uint": "integer",
    "float": "float",
    "bool": "boolean",
    "datetime": "timestamp",
    "string": "string",
    "str": "string",
    "category": "string",
}


@public
class PredictionError(ModelServingException):
    """A request could not be served; carries the HTTP status and the structured error detail."""

    def __init__(self, status_code: int, detail: dict[str, Any]):
        super().__init__(detail.get("message", ""))
        self.status_code = status_code
        self.detail = detail


def _http_error(
    status_code: int,
    code: str,
    message: str,
    errors: list[dict[str, Any]] | None = None,
    schema_id: str | None = None,
) -> Exception:
    """Build the exception the KServe wrapper renders with `status_code`; a plain error outside a serving pod."""
    detail: dict[str, Any] = {"code": code, "message": message}
    if schema_id is not None:
        detail["schema_id"] = schema_id
    if errors:
        detail["errors"] = errors
    try:
        from fastapi import HTTPException
    except ImportError:
        try:
            from starlette.exceptions import HTTPException
        except ImportError:
            return PredictionError(status_code, detail)
    return HTTPException(status_code=status_code, detail=detail)


def _revision_schema(deployment):
    """The schema this pod's revision names, which during a rolling update may be older than the deployment's current one."""
    own_id = os.environ.get(MODEL_SERVING.DEPLOYMENT_SCHEMA_ID_ENV_VAR)
    if not own_id or own_id == deployment.schema_id:
        return deployment.schema
    from hsml.engine import serving_engine

    return serving_engine.ServingEngine()._read_schema(deployment._predictor, own_id)


def _revision_model(deployment):
    """The model this pod's revision serves: the pod's MODEL_NAME and MODEL_VERSION win over the deployment's current ones."""
    name = os.environ.get("MODEL_NAME")
    version = os.environ.get("MODEL_VERSION")
    if (
        name
        and version
        and (
            name != getattr(deployment, "model_name", None)
            or str(version) != str(getattr(deployment, "model_version", None))
        )
    ):
        return deployment._model_api._get(
            name, int(version), deployment.model_registry_id
        )
    return deployment.get_model()


def _revision_feature_view(deployment):
    """The feature view a model-less pod's revision serves: its own env vars win over the deployment's current view."""
    name = os.environ.get(MODEL_SERVING.FEATURE_VIEW_NAME_ENV_VAR)
    version = os.environ.get(MODEL_SERVING.FEATURE_VIEW_VERSION_ENV_VAR)
    if (
        name
        and version
        and (
            name != getattr(deployment, "feature_view_name", None)
            or str(version) != str(getattr(deployment, "feature_view_version", None))
        )
    ):
        import hopsworks

        if not hopsworks._connected_project:
            raise ModelServingException(
                f"The revision serves feature view {name} v{version} but the pod has "
                "no project connection to resolve it; the serving environment must "
                "log in to Hopsworks before the predictor starts."
            )
        return hopsworks._connected_project.get_feature_store().get_feature_view(
            name, int(version)
        )
    return deployment.get_feature_view(init=False)


def _revision_training_dataset_version(deployment, model):
    if model is not None:
        return model.training_dataset_version
    own = os.environ.get(MODEL_SERVING.TRAINING_DATASET_VERSION_ENV_VAR)
    return int(own) if own else deployment.training_dataset_version


@public
def run_kserve_wrapper() -> None:
    """Replace this process with the KServe wrapper that serves the `Predict` class of `SCRIPT_PATH`.

    Deployments without a model artifact are started as `python <script>`;
    calling this from the script's `__main__` block gives them the same
    server, payload handling, and feature logger as model deployments.
    """
    launcher = shutil.which(_LAUNCHER)
    if launcher is None:
        raise ModelServingException(
            f"{_LAUNCHER} is not on PATH. Deployments served by the default predictor "
            "need an environment derived from a Hopsworks inference image."
        )
    name = os.environ.get("DEPLOYMENT_NAME")
    if not name:
        raise ModelServingException(
            "DEPLOYMENT_NAME is not set; run_kserve_wrapper() only works inside a "
            "Hopsworks deployment."
        )
    os.execv(launcher, [launcher, "--model_name", name, "--api_protocol", "v1"])


def _log_queue_size() -> int:
    """Rows retained by the logging worker; the wrapper reads the same limit."""
    try:
        return max(1, int(os.environ.get("FEATURE_LOGGER_QUEUE_SIZE", "1000")))
    except ValueError:
        return 1000


def _worth_logging(count: int, rows: int = 1) -> bool:
    return count == rows or count // 100 != (count - rows) // 100


def _int_or_none(value):
    try:
        return int(value) if value not in (None, "") else None
    except ValueError:
        return None


def _take(values, start: int, stop: int):
    if values is None:
        return None
    if hasattr(values, "iloc"):
        return values.iloc[start:stop]
    return values[start:stop]


def _row_slices(rows, feature_vectors, predictions, max_rows: int):
    """A request's rows in pieces of at most `max_rows`, with each piece's offset in the request.

    The receiver's row limit is per post, so one request larger than it has to become several batches.
    """
    count = len(rows)
    if count <= max_rows:
        yield 0, rows, feature_vectors, predictions
        return
    for start in range(0, count, max_rows):
        stop = min(count, start + max_rows)
        yield (
            start,
            _take(rows, start, stop),
            _take(feature_vectors, start, stop),
            _take(predictions, start, stop),
        )


def _logging_transport(feature_view) -> str:
    """The transport this pod logs through: the deployment's marker, else the view's."""
    for name in ("SERVING_FEATURE_LOGGING", "HOPSWORKS_FEATURE_LOGGING_TRANSPORT"):
        value = os.environ.get(name, "").strip().lower()
        if value in ("realtime", "job"):
            return value
    logging = getattr(feature_view, "feature_logging", None)
    transport = getattr(logging, "transport", None)
    return transport if transport in ("realtime", "job") else "realtime"


def _max_event_rows() -> int:
    """Rows one post may carry: the inference logger's own limit, so a group never exceeds it."""
    return _positive_env("HOPSWORKS_FEATURE_LOGGER_MAX_EVENT_ROWS", 512)


def _batch_limits() -> tuple[int, float]:
    """Bytes and seconds after which a coalesced post goes out even under backlog."""
    return (
        _positive_env("FEATURE_LOGGER_BATCH_BYTES", 1024 * 1024),
        float(_positive_env("FEATURE_LOGGER_BATCH_SECONDS", 5)),
    )


class _LogWorker:
    """Runs the feature view's `log()` for queued requests on one background thread.

    The request thread only enqueues; a full queue drops the request's rows and
    counts the drop, a failing `log()` is counted and logged. At most once,
    best effort: rows still queued when the process ends are lost.
    """

    # The frame building holds the GIL for milliseconds; started the instant a
    # request is queued it lands in that request's response tail, and the
    # deferral gains nothing. Yielding first lets the response go out.
    RESPONSE_GRACE_SECONDS = 0.002

    def __init__(self, target, maxsize: int, budget=None):
        self._target = target
        self._queue: queue.Queue = queue.Queue()
        self._max_bytes = _positive_env(
            "HOPSWORKS_FEATURE_LOGGER_MAX_BUFFER_BYTES", 64 * 1024 * 1024
        )
        self._budget = budget or _BufferBudget(maxsize, self._max_bytes)
        self._closed = False
        self._admission_lock = threading.Lock()
        self.dropped = 0
        self.failed = 0
        self._thread = threading.Thread(
            target=self._run, name="hsml-feature-log", daemon=True
        )
        self._thread.start()
        atexit.register(self._close)

    def _submit(self, item) -> bool:
        with self._admission_lock:
            return self._enqueue(item)

    def _enqueue(self, item) -> bool:
        # Admission is a row bound; bytes are known only once the worker has
        # built the Arrow batch, and it is the worker that enforces them.
        rows = len(item[0])
        size = 0
        if self._closed or not self._budget._acquire(rows, size):
            self.dropped += rows
            if _worth_logging(self.dropped, rows):
                _logger.error(
                    "Feature logging admission rejected (%d rows dropped so far)",
                    self.dropped,
                )
            return False
        self._queue.put_nowait((item, rows, size))
        return True

    def _run(self) -> None:
        # One request posts at once when nothing else is waiting. Under a
        # backlog requests are taken together until the queue is empty, the
        # byte cap or the age cap, so the post count falls with the load
        # instead of the latency rising with it.
        max_rows, batch_seconds = _max_event_rows(), _batch_limits()[1]
        while True:
            queued = self._queue.get()
            if queued is None:
                self._queue.task_done()
                return
            group, rows, size = [queued], queued[1], queued[2]
            started = time.monotonic()
            if self._queue.empty():
                time.sleep(self.RESPONSE_GRACE_SECONDS)
            while (
                rows < max_rows
                and time.monotonic() - started < batch_seconds
                and not self._queue.empty()
            ):
                more = self._queue.get_nowait()
                if more is None:
                    self._queue.put_nowait(None)
                    break
                group.append(more)
                rows += more[1]
                size += more[2]
            try:
                # One reservation for the whole group: the async logger transfers
                # a combined post's rows from the reservation active on this
                # thread, and stacked per-request reservations would leave only
                # the last request's allowance visible.
                with _Reservation(self._budget, rows, size):
                    self._target([item for item, _rows, _size in group])
            except Exception as error:  # noqa: BLE001 - logging must not take serving down
                self.failed += rows
                if _worth_logging(self.failed, rows):
                    _logger.error(
                        "Feature logging failed (%s; %d rows failed so far)",
                        type(error).__name__,
                        self.failed,
                    )
            finally:
                for _ in group:
                    self._queue.task_done()

    def _wait(self, timeout: float) -> bool:
        """Block until every queued request was handled or `timeout` seconds passed."""
        deadline = time.monotonic() + timeout
        with self._queue.all_tasks_done:
            while self._queue.unfinished_tasks:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    return False
                self._queue.all_tasks_done.wait(remaining)
        return True

    def _close(self, timeout: float | None = None) -> bool:
        if timeout is None:
            timeout = _positive_env("HOPSWORKS_FEATURE_LOGGER_SHUTDOWN_SECONDS", 5)
        deadline = time.monotonic() + max(0.0, timeout)
        with self._admission_lock:
            self._closed = True
        drained = self._wait(max(0.0, deadline - time.monotonic()))
        if not drained:
            while True:
                try:
                    queued = self._queue.get_nowait()
                except queue.Empty:
                    break
                if queued is not None:
                    _, rows, size = queued
                    self.dropped += rows
                    self._budget._release(rows, size)
                self._queue.task_done()
        if self._thread.is_alive():
            try:
                self._queue.put_nowait(None)
                self._thread.join(max(0.0, deadline - time.monotonic()))
            except queue.Full:
                return False
        return drained


@public
class DefaultPredict:
    """Predictor for deployments whose requests are described by a deployment schema.

    Validates each request against the schema, looks up and transforms the
    feature vector through the feature view, runs the model when the
    deployment has one, and logs the request when the feature view has
    logging enabled. Without a model it returns the transformed vectors.
    Subclass it and override `load_model` or `model_predict` for models the
    default loader cannot handle.

    Example:
        ```python
        # predictor.py, deployed with model.deploy(script_file="predictor.py",
        # default_predictor=True) so the schema is still inferred
        from hsml.deployment.default_predictor import DefaultPredict


        class Predict(DefaultPredict):
            def load_model(self, model_files_path):
                return my_framework.load(model_files_path)

            def model_predict(self, feature_vectors):
                return self.model.predict_proba(
                    feature_vectors[self.model_input_columns]
                )
        ```
    """

    def __init__(self, deployment, async_logger=None):
        self.deployment = deployment
        # Everything below comes from the pod's own revision (its env vars and
        # the model they name), never from the deployment's current revision,
        # which during a rollout or rollback can be newer than this pod.
        self.hopsworks_model = _revision_model(deployment)
        subject = (
            f"model '{self.hopsworks_model.name}' v{self.hopsworks_model.version}"
            if self.hopsworks_model is not None
            else f"deployment '{deployment.name}'"
        )

        self.schema = _revision_schema(deployment)
        if self.schema is None:
            raise ModelServingException(
                f"Deployment '{deployment.name}' has no deployment schema: the env var "
                f"{MODEL_SERVING.DEPLOYMENT_SCHEMA_ID_ENV_VAR} is missing or the schema file "
                "it names is gone. Redeploy, or set deployment.schema and save()."
            )

        self.training_dataset_version = _revision_training_dataset_version(
            deployment, self.hopsworks_model
        )
        if self.hopsworks_model is not None:
            # the same call a hand-written predictor makes: inside a deployment
            # it also initialises the view for serving on the model's training
            # dataset
            self.feature_view = self.hopsworks_model.get_feature_view()
        else:
            self.feature_view = _revision_feature_view(deployment)
        if self.feature_view is None:
            if self.schema.serving_keys or self.schema.feature_view:
                raise ModelServingException(
                    f"No feature view is linked to {subject}, but its deployment schema "
                    "was inferred from one. Register the model with "
                    "create_model(feature_view=...) or redeploy."
                )
            if self.hopsworks_model is None:
                raise ModelServingException(
                    f"{subject} has neither a model nor a feature view; nothing to serve."
                )
            # a model served on its passed features alone: no lookup, no
            # transformation, no feature logging
            self.training_dataset_version = None
            self.logging_enabled = False
            self._log_worker = None
            self.monitoring_configs = []
            self.reserved_columns = []
            self.max_batch_rows = self.schema.max_batch_rows
            # No feature view means nothing to log, but close() still runs.
            self._log_worker = self._arrow_builder = self._file_transport = None
            self._async_logger = async_logger
            self.model = self.load_model(os.environ.get("MODEL_FILES_PATH", "."))
            self._check_model_inputs_against_schema()
            _logger.info(
                "DefaultPredict ready for model '%s' v%s without a feature view: schema %s "
                "with %d passed features",
                self.hopsworks_model.name,
                self.hopsworks_model.version,
                self.schema.schema_id,
                len(self.schema.passed_features),
            )
            return
        recorded = self.schema.feature_view or {}
        if recorded.get("name") is not None and (
            recorded["name"] != self.feature_view.name
            or int(recorded["version"]) != int(self.feature_view.version)
        ):
            raise ModelServingException(
                f"The deployment schema was published for feature view "
                f"'{recorded['name']}' v{recorded['version']} but the deployment serves "
                f"'{self.feature_view.name}' v{self.feature_view.version}. Redeploy."
            )

        _check_training_dataset_version(
            self.feature_view,
            self.training_dataset_version,
            subject,
            "Redeploy with a training dataset version.",
        )
        published = self.schema.training_dataset_version
        if (
            published is not None
            and self.training_dataset_version is not None
            and int(published) != int(self.training_dataset_version)
        ):
            raise ModelServingException(
                f"Deployment schema {self.schema.schema_id} was published for training "
                f"dataset v{published} but this revision serves v"
                f"{self.training_dataset_version}. Redeploy so the schema and the "
                "statistics agree."
            )

        logging_wanted = bool(getattr(self.feature_view, "logging_enabled", False))
        self.logging_transport = (
            _logging_transport(self.feature_view) if logging_wanted else None
        )
        # The job transport writes to its own process; only realtime needs the
        # wrapper's logger to reach the sidecar.
        if logging_wanted and self.logging_transport == "job":
            async_logger = None
        elif logging_wanted and async_logger is None:
            _logger.warning(
                "Feature logging is enabled on feature view '%s' v%s but the serving "
                "wrapper provided no feature logger; requests of %s are not logged.",
                self.feature_view.name,
                self.feature_view.version,
                subject,
            )
        self.logging_enabled = logging_wanted and (
            async_logger is not None or self.logging_transport == "job"
        )
        self.monitoring_configs = self._monitoring_configs()
        if self.monitoring_configs and not self.logging_enabled:
            _logger.warning(
                "Monitoring configs %s exist for %s but feature logging is disabled on "
                "feature view '%s' v%s; they will see no new rows. Call "
                "feature_view.enable_logging() and restart the deployment.",
                [c.name for c in self.monitoring_configs],
                subject,
                self.feature_view.name,
                self.feature_view.version,
            )
        self.reserved_columns = self._reserved_columns()
        self.max_batch_rows = self.schema.max_batch_rows

        if self.hopsworks_model is None:
            self.feature_view.init_serving(
                training_dataset_version=self.training_dataset_version
            )
        self._log_worker = None
        self._arrow_builder = None
        self._async_logger = async_logger
        self._file_transport = None
        if self.logging_enabled and self.logging_transport == "job":
            from hopsworks_common.core.feature_logging_arrow import (
                _ArrowBatchBuilder,
            )
            from hopsworks_common.core.feature_logging_file import (
                _expose_metrics,
                _FileLogOptions,
                _FileLogTransport,
            )

            self._arrow_builder = _ArrowBatchBuilder(
                self.feature_view, self.training_dataset_version
            )
            self._file_transport = _FileLogTransport(
                _FileLogOptions(
                    self.feature_view.name,
                    self.feature_view.version,
                    schema_id=self.schema.schema_id,
                )
            )
            _logger.info("Feature logging transport: job (file buffer)")
            self._log_worker = _LogWorker(self._log_now, _log_queue_size())
            _expose_metrics(self._file_transport, self._log_worker)
        elif self.logging_enabled:
            self.feature_view.init_feature_logger(async_logger)
            from hopsworks_common.core.feature_logging_arrow import (
                _select_arrow_builder,
            )

            self._arrow_builder, logging_mode = _select_arrow_builder(
                self.feature_view, self.training_dataset_version, async_logger
            )
            _logger.info("Feature logging transport: %s", logging_mode)
            delivery_worker = getattr(async_logger, "_async_worker_thread", None)
            self._log_worker = _LogWorker(
                self._log_now,
                _log_queue_size(),
                getattr(delivery_worker, "_budget", None),
            )

        self.model = None
        self.model_input_columns: list[str] | None = None
        self.model_input_is_tensor = False
        if self.hopsworks_model is not None:
            self.model = self.load_model(os.environ.get("MODEL_FILES_PATH", "."))
            self.check_model_input_contract()

        _logger.info(
            "DefaultPredict ready for %s: schema %s with %d fields (%d unresolved), "
            "feature logging %s, %d monitoring config(s)",
            subject,
            self.schema.schema_id,
            len(self.schema.columns),
            len(self.schema.unresolved),
            "on" if self.logging_enabled else "off",
            len(self.monitoring_configs),
        )

    # region Startup

    def _monitoring_configs(self) -> list:
        try:
            return list(self.deployment.get_monitoring_configs() or [])
        except Exception as err:  # noqa: BLE001 - monitoring is observability, not serving
            _logger.warning("Could not list monitoring configs: %s", err)
            return []

    def _reserved_columns(self) -> list[str]:
        if not self.logging_enabled:
            return []
        logging = getattr(self.feature_view, "feature_logging", None)
        columns = getattr(logging, "extra_logging_columns", None) or []
        declared = {c.name for c in columns}
        known = {f.name for f in self.schema.extra_logging_features}
        undeclared_in_schema = sorted(declared - known - set(RESERVED_LOGGING_COLUMNS))
        if undeclared_in_schema:
            _logger.warning(
                "Extra logging columns %s are declared on the feature view but not in "
                "deployment schema %s; they are logged as null. Run "
                "deployment.reinfer_schema() and save() to accept them.",
                undeclared_in_schema,
                self.schema.schema_id,
            )
        return [name for name in RESERVED_LOGGING_COLUMNS if name in declared]

    @public
    def load_model(self, model_files_path: str) -> Any:
        """Load the single pickle or joblib file under `model_files_path`.

        Parameters:
            model_files_path: Directory holding the model files (`MODEL_FILES_PATH` in the pod).

        Returns:
            The loaded model object.

        Raises:
            hopsworks.client.exceptions.ModelServingException: If there is not exactly one candidate file; override this method or pass your own script then.
        """
        candidates = []
        for root, _, files in os.walk(model_files_path):
            for file_name in files:
                if file_name.lower().endswith(_MODEL_FILE_EXTENSIONS):
                    candidates.append(os.path.join(root, file_name))
        if len(candidates) != 1:
            found = ", ".join(sorted(candidates)) or "none"
            raise ModelServingException(
                f"The default predictor loads exactly one .pkl, .pickle, or .joblib file "
                f"from {model_files_path}; found: {found}. Subclass DefaultPredict and "
                "override load_model, or deploy with your own script_file."
            )
        try:
            import joblib
        except ImportError:
            import pickle

            with open(candidates[0], "rb") as f:
                return pickle.load(f)  # noqa: S301 - model files are the project's own
        return joblib.load(candidates[0])

    def _transformed_columns(self) -> list[tuple[str, str | None]]:
        features = self.feature_view.get_training_dataset_schema(
            self.training_dataset_version
        )
        return [
            (f.name, (str(f.type).lower() if f.type is not None else None))
            for f in features
            if not getattr(f, "label", False)
            and not getattr(f, "inference_helper_column", False)
            and not getattr(f, "training_helper_column", False)
        ]

    @public
    def check_model_input_contract(self) -> None:
        """Fail unless the model's input schema is served by the transformed feature view schema.

        Columnar inputs must all exist among the transformed columns with a
        compatible type family; a tensor input must be a single tensor whose
        last dimension is the number of transformed columns. Nothing is
        guessed: a missing or incompatible input schema raises.

        Raises:
            hopsworks.client.exceptions.ModelServingException: On any mismatch, naming the columns or shapes involved.
        """
        model_schema = self.hopsworks_model.model_schema
        if not model_schema:
            raise ModelServingException(
                f"Model '{self.hopsworks_model.name}' v{self.hopsworks_model.version} has "
                "no model schema. Save it with create_model(feature_view=...) so the input "
                "schema is inferred, or set model_schema explicitly."
            )
        model_schema = humps.decamelize(model_schema)
        input_schema = model_schema.get("input_schema") or {}
        transformed = self._transformed_columns()
        transformed_types = dict(transformed)

        if input_schema.get("columnar_schema"):
            columns = input_schema["columnar_schema"]
            names = [c.get("name") for c in columns]
            if any(name is None for name in names):
                raise ModelServingException(
                    "The model input schema has unnamed columns; the default predictor "
                    "needs column names to select the model inputs from the feature vector."
                )
            missing = [n for n in names if n not in transformed_types]
            if missing:
                raise ModelServingException(
                    f"Model input columns {missing} are not in the transformed feature "
                    f"vector of feature view '{self.feature_view.name}' "
                    f"v{self.feature_view.version} (columns: {list(transformed_types)})."
                )
            incompatible = []
            for c in columns:
                model_family = _family_of_any(c.get("type"))
                feature_family = _family(transformed_types[c["name"]])
                if model_family and feature_family and model_family != feature_family:
                    incompatible.append(
                        f"{c['name']}: model {c.get('type')}, feature view "
                        f"{transformed_types[c['name']]}"
                    )
            if incompatible:
                raise ModelServingException(
                    "Model input columns have incompatible types: "
                    + "; ".join(incompatible)
                )
            self.model_input_columns = names
            return

        tensors = input_schema.get("tensor_schema")
        if tensors:
            if len(tensors) != 1:
                raise ModelServingException(
                    f"The model input schema has {len(tensors)} tensors; the default "
                    "predictor supports a single input tensor."
                )
            shape = list(tensors[0].get("shape") or [])
            width = shape[-1] if shape else None
            if width not in (None, -1, len(transformed)):
                raise ModelServingException(
                    f"The model input tensor has shape {shape} but the transformed feature "
                    f"vector has {len(transformed)} columns."
                )
            self.model_input_is_tensor = True
            self.model_input_columns = [name for name, _ in transformed]
            return

        raise ModelServingException(
            "The model input schema has neither a columnar nor a tensor schema; the "
            "default predictor cannot select the model inputs."
        )

    def _check_model_inputs_against_schema(self) -> None:
        """Without a feature view the model inputs are the passed features.

        A legacy model schema, when present, must agree with them.
        """
        input_schema = (
            humps.decamelize(self.hopsworks_model.model_schema or {}).get(
                "input_schema"
            )
            or {}
        )
        columns = [
            c for c in (input_schema.get("columnar_schema") or []) if c.get("name")
        ]
        passed = {f.name: f.type for f in self.schema.passed_features}
        if not columns:
            # the passed features are the model inputs, in the schema's order
            self.model_input_columns = list(passed)
            self.model_input_is_tensor = False
            return
        missing = [c["name"] for c in columns if c["name"] not in passed]
        if missing:
            raise ModelServingException(
                f"Model input columns {missing} are not passed features of the deployment "
                f"schema (passed: {sorted(passed)})."
            )
        incompatible = [
            f"{c['name']}: model {c.get('type')}, schema {passed[c['name']]}"
            for c in columns
            if _family_of_any(c.get("type"))
            and _family(passed[c["name"]])
            and _family_of_any(c.get("type")) != _family(passed[c["name"]])
        ]
        if incompatible:
            raise ModelServingException(
                "Model input columns have incompatible types: "
                + "; ".join(incompatible)
            )
        self.model_input_columns = [c["name"] for c in columns]
        self.model_input_is_tensor = False

    # endregion

    # region Request handling

    @public
    def prepare_rows(self, inputs: Any) -> list[dict[str, Any]]:
        """Validate the request rows against the schema.

        Parameters:
            inputs: The request rows, as objects keyed by field name or arrays in schema order.

        Returns:
            The rows as dicts keyed by field name.

        Raises:
            fastapi.HTTPException: 400 with the structured errors on a mismatch, 413 on an oversize batch.
        """
        if isinstance(inputs, (list, tuple)) and len(inputs) > self.max_batch_rows:
            raise _http_error(
                413,
                "BATCH_TOO_LARGE",
                f"The request has {len(inputs)} rows; deployment '{self.deployment.name}' "
                f"accepts at most {self.max_batch_rows}.",
                schema_id=self.schema.schema_id,
            )
        errors = self.schema.validate_instances(inputs, max_rows=self.max_batch_rows)
        if errors:
            raise _http_error(
                400,
                "SCHEMA_VALIDATION",
                f"Prediction request does not match the deployment schema of "
                f"'{self.deployment.name}'. Expected fields (in order): "
                + ", ".join(self.schema.names),
                errors=errors,
                schema_id=self.schema.schema_id,
            )
        return self.schema.rows(list(inputs))

    def _split(self, rows: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
        groups: dict[str, list[dict[str, Any]]] = {
            "serving_keys": [],
            "passed_features": [],
            "request_parameters": [],
            "extra_logging_features": [],
        }
        for row in rows:
            split = self.schema.split_row(row)
            for group in groups:
                groups[group].append(split[group])
        return groups

    @public
    def fetch_feature_vectors(self, rows: list[dict[str, Any]]) -> Any:
        """Look up and transform the feature vectors for `rows`.

        Parameters:
            rows: Validated rows as returned by `prepare_rows`.

        Returns:
            A pandas DataFrame in the transformed schema order, one row per input row.

        Raises:
            fastapi.HTTPException: 404 when an entity is missing, 422 when a transformation fails, 503 when the feature store is unreachable.
        """
        groups = self._split(rows)
        if not self.schema.serving_keys:
            return self._passed_feature_vectors(groups)
        entries = groups["serving_keys"]
        passed = groups["passed_features"] if self.schema.passed_features else None
        request_parameters = (
            groups["request_parameters"] if self.schema.request_parameters else None
        )
        try:
            return self.feature_view.get_feature_vectors(
                entry=entries,
                passed_features=passed,
                request_parameters=request_parameters,
                return_type="pandas",
                allow_missing=False,
                logging_data=self.logging_enabled,
            )
        except FeatureStoreException as err:
            raise self._lookup_failure(
                err, entries, passed, request_parameters
            ) from err
        except (ConnectionError, TimeoutError, OSError) as err:
            raise _http_error(
                503,
                "FEATURE_STORE_UNAVAILABLE",
                f"The feature store could not be reached ({type(err).__name__}).",
            ) from err
        except Exception as err:  # noqa: BLE001 - user transformations may raise anything
            raise self._transformation_failed(err) from err

    def _transformation_failed(self, err: Exception) -> Exception:
        message = (
            f"A transformation of feature view '{self.feature_view.name}' "
            f"v{self.feature_view.version} raised {type(err).__name__}."
        )
        untyped = [f.name for f in self.schema.request_parameters if f.type is None]
        if untyped:
            message += (
                f" The request parameters {', '.join(untyped)} have no recorded type,"
                " so the values sent may not be what the transformation expects."
            )
        return _http_error(422, "TRANSFORMATION_FAILED", message)

    def _passed_feature_vectors(self, groups: dict[str, list[dict[str, Any]]]) -> Any:
        """Feature vectors from the passed features alone: nothing is looked up.

        With a feature view, its on-demand and model-dependent transformations
        still apply, and the untransformed frame travels in `attrs` for logging.
        """
        import pandas as pd

        untransformed = pd.DataFrame(
            groups["passed_features"],
            columns=[f.name for f in self.schema.passed_features],
        )
        if self.feature_view is None:
            return untransformed
        try:
            if self.schema.request_parameters:
                untransformed = self.feature_view.compute_on_demand_features(
                    untransformed,
                    request_parameters=groups["request_parameters"],
                    return_type="pandas",
                )
            transformed = self.feature_view.transform(
                untransformed, return_type="pandas"
            )
        except Exception as err:  # noqa: BLE001 - user transformations may raise anything
            raise self._transformation_failed(err) from err
        transformed.attrs["untransformed"] = untransformed
        return transformed

    def _lookup_failure(self, err, entries, passed, request_parameters) -> Exception:
        """Turn a failed lookup into a 404 naming the rows without an entity, or a 400 with the feature store message."""
        try:
            frame = self.feature_view.get_feature_vectors(
                entry=entries,
                passed_features=passed,
                request_parameters=request_parameters,
                return_type="pandas",
                allow_missing=True,
                transform=False,
                on_demand_features=False,
            )
        except Exception as retry_err:  # noqa: BLE001 - reported as unavailable below
            _logger.error("Locating the missing rows failed", exc_info=retry_err)
            return _http_error(
                503,
                "FEATURE_STORE_UNAVAILABLE",
                f"The feature lookup failed ({type(err).__name__}) and the missing rows "
                f"could not be located ({type(retry_err).__name__}).",
            )
        passed_names = {f.name for f in self.schema.passed_features}
        lookup_columns = [c for c in frame.columns if c not in passed_names]
        missing_rows = []
        for row_index, (_, row) in enumerate(frame.iterrows()):
            values = row[lookup_columns] if lookup_columns else row
            if all(_is_null(v) for v in values):
                missing_rows.append(row_index)
        if not missing_rows:
            return _http_error(
                400,
                "FEATURE_LOOKUP_FAILED",
                f"The feature store rejected the lookup ({type(err).__name__}).",
            )
        key_names = ", ".join(f.name for f in self.schema.serving_keys)
        return _http_error(
            404,
            "ENTITY_NOT_FOUND",
            f"No entity found for {len(missing_rows)} of {len(entries)} rows "
            f"(serving keys: {key_names}).",
            errors=[
                {
                    "row": r,
                    "field": key_names,
                    "reason": "no entity with these serving keys",
                }
                for r in missing_rows
            ],
            schema_id=self.schema.schema_id,
        )

    @public
    def model_predict(self, feature_vectors: Any) -> Any:
        """Run the model on the transformed feature vectors, or return them unchanged when there is no model.

        Parameters:
            feature_vectors: The DataFrame returned by `fetch_feature_vectors`.

        Returns:
            The model's predictions as a list, or `feature_vectors` itself without a model.

        Raises:
            fastapi.HTTPException: 500 when the model raises.
        """
        if self.model is None:
            return feature_vectors
        x = feature_vectors[self.model_input_columns]
        if self.model_input_is_tensor:
            x = x.to_numpy()
        try:
            predictions = self.model.predict(x)
        except Exception as err:  # noqa: BLE001 - reported as MODEL_FAILED
            raise _http_error(
                500, "MODEL_FAILED", f"The model raised {type(err).__name__}."
            ) from err
        return predictions.tolist() if hasattr(predictions, "tolist") else predictions

    @public
    def log(
        self,
        rows: list[dict[str, Any]],
        feature_vectors: Any,
        predictions: Any,
        request_id: str | None = None,
    ) -> None:
        """Queue the request for logging through the feature view when logging is enabled.

        The logging frame is built and handed to the wrapper's async logger on a
        background thread, so this returns as soon as the request is queued. A
        full queue drops the request's rows and counts the drop; a failure on the
        worker is counted and logged and never fails a prediction.

        Parameters:
            rows: Validated rows as returned by `prepare_rows`.
            feature_vectors: The DataFrame returned by `fetch_feature_vectors`, carrying the logging metadata.
            predictions: The model output, ignored without a model.
            request_id: Correlation id stored with every logged row.
        """
        if not self.logging_enabled:
            return
        try:
            self._log_worker._submit(
                (
                    rows,
                    feature_vectors,
                    predictions,
                    request_id,
                    datetime.now(timezone.utc),
                )
            )
        except Exception as error:  # noqa: BLE001 - logging cannot fail a prediction
            self._log_worker.failed += len(rows)
            if _worth_logging(self._log_worker.failed, len(rows)):
                _logger.error(
                    "Feature logging admission failed: %s", type(error).__name__
                )

    @public
    def close(self, timeout: float = 5.0) -> bool:
        """Drain the queued log requests.

        Registered to run at interpreter exit; call it earlier for an orderly
        shutdown.

        Parameters:
            timeout: Seconds to wait for the queue to empty and the worker to stop.

        Returns:
            `True` when the queue emptied in time.
        """
        deadline = time.monotonic() + timeout
        drained = self._log_worker._close(timeout) if self._log_worker else True
        if self._file_transport is not None:
            # The writer uploads what it holds within what is left of the same
            # budget, then the commit job is asked to pick it up so a stopped
            # deployment's rows reach the log.
            drained = (
                self._file_transport._close(max(0.5, deadline - time.monotonic()))
                and drained
            )
            self._trigger_commit_job()
        return drained

    def _trigger_commit_job(self) -> None:
        from hopsworks_common.core.feature_logging_file import _commit_job_name
        from hopsworks_common.core.job_api import JobApi

        name = _commit_job_name(self.feature_view.name, self.feature_view.version)
        try:
            job = JobApi().get_job(name)
            if job is not None and not any(
                e.success is None for e in job.get_executions() or []
            ):
                job.run(await_termination=False)
        except Exception as error:  # noqa: BLE001 - the pod is stopping
            _logger.warning(
                "Feature log commit job %s not triggered: %s",
                name,
                type(error).__name__,
            )

    def _log_now(self, requests) -> None:
        """Log one or more queued requests, one post when the Arrow path is on.

        Parameters:
            requests: `(rows, feature_vectors, predictions, request_id, log_time)` per request.
        """
        if getattr(self._async_logger, "_arrow_disabled", False):
            self._arrow_builder = None
        if self._arrow_builder is None:
            for rows, feature_vectors, predictions, request_id, _log_time in requests:
                self._log_legacy(rows, feature_vectors, predictions, request_id)
            return
        # Requests are built one at a time and a post goes out as soon as the
        # next batch would push it over the receiver's row or byte limit, or
        # once it holds batch_bytes of Arrow, so the group is never held whole.
        max_rows, max_bytes = _max_event_rows(), self._arrow_builder._max_bytes
        batch_bytes = _batch_limits()[0]
        chunk, chunk_rows, chunk_bytes = [], 0, 0
        first = requests[0]

        def flush():
            nonlocal chunk, chunk_rows, chunk_bytes
            if not chunk:
                return
            combined = self._arrow_builder._combine(chunk)
            if self._file_transport is not None:
                combined = self._arrow_builder._complete(
                    combined, self._file_column_values()
                )
                self._file_transport._submit(
                    self._arrow_builder._serialize(combined), combined.num_rows
                )
            else:
                self._post_arrow(
                    self._arrow_builder._serialize(combined),
                    combined.num_rows,
                    first[3],
                    first[4],
                )
            chunk, chunk_rows, chunk_bytes = [], 0, 0

        for rows, feature_vectors, predictions, request_id, log_time in requests:
            for start, row_slice, vector_slice, prediction_slice in _row_slices(
                rows, feature_vectors, predictions, max_rows
            ):
                batch = self._arrow_builder._build_batch(
                    vector_slice,
                    prediction_slice if self.hopsworks_model is not None else None,
                    self._extra_logging_values(row_slice, start),
                    request_id,
                    log_time,
                )
                if chunk and (
                    chunk_rows + batch.num_rows > max_rows
                    or chunk_bytes + batch.nbytes > max_bytes * 0.9
                ):
                    flush()
                chunk.append(batch)
                chunk_rows += batch.num_rows
                chunk_bytes += batch.nbytes
                if chunk_rows >= max_rows or chunk_bytes >= batch_bytes:
                    flush()
        flush()

    def _file_column_values(self) -> dict[str, Any]:
        """What the inference logger reads from the event headers, for a chunk that has none."""
        model = self.hopsworks_model
        return {
            "model_name": getattr(model, "name", None),
            "model_version": "None" if model is None else str(model.version),
            "td_version": self.training_dataset_version,
            "deployment_name": os.environ.get("DEPLOYMENT_NAME", self.deployment.name),
            "deployment_version": _int_or_none(os.environ.get("DEPLOYMENT_VERSION")),
            "deployment_schema_id": self.schema.schema_id,
        }

    def _post_arrow(self, payload, rows, request_id, log_time) -> None:
        # The event headers describe the first request; request id and log time
        # of every other request in the post travel as columns of the batch.
        from hopsworks_common import client

        if payload:
            attributes = {
                "content-type": "application/vnd.apache.arrow.stream",
                "ce-specversion": "1.0",
                "ce-type": "serving.hops.works.logging.features.arrow",
                "ce-id": str(uuid.uuid4()),
                "ce-source": getattr(self._async_logger, "_source", None)
                or "http://localhost:8099",
                "ce-time": (log_time or datetime.now(timezone.utc)).isoformat(),
                "ce-hopsprojectid": str(client._get_instance()._project_id),
                "ce-hopsfsid": str(self.feature_view._feature_store_id),
                "ce-hopsfeatureview": self.feature_view.name,
                "ce-hopsfvversion": str(self.feature_view.version),
                "ce-hopsrequestid": request_id or str(uuid.uuid4()),
                "ce-hopsschemaid": self.schema.schema_id,
                "ce-hopsdeplname": os.environ.get(
                    "DEPLOYMENT_NAME", self.deployment.name
                ),
            }
            if self.training_dataset_version is not None:
                attributes["ce-hopstdversion"] = str(self.training_dataset_version)
            if self.hopsworks_model is not None:
                attributes["ce-hopsmodelname"] = self.hopsworks_model.name
                attributes["ce-hopsmodelversion"] = str(self.hopsworks_model.version)
            if os.environ.get("DEPLOYMENT_VERSION"):
                attributes["ce-hopsdeplversion"] = os.environ["DEPLOYMENT_VERSION"]
            self._async_logger.log_batch(payload, attributes, rows=rows)

    def _log_legacy(self, rows, feature_vectors, predictions, request_id) -> None:
        extra = self._extra_logging_values(rows)
        untransformed = getattr(feature_vectors, "attrs", {}).get("untransformed")
        self.feature_view.log(
            feature_vectors if untransformed is None else None,
            untransformed_features=untransformed,
            transformed_features=feature_vectors if untransformed is not None else None,
            predictions=predictions if self.hopsworks_model is not None else None,
            extra_logging_features=extra,
            request_id=request_id,
            training_dataset_version=self.training_dataset_version,
            model=self.hopsworks_model,
        )

    def _extra_logging_values(
        self, rows, start: int = 0
    ) -> list[dict[str, Any]] | None:
        client_columns = [f.name for f in self.schema.extra_logging_features]
        if not client_columns and not self.reserved_columns:
            return None
        deployment_name = os.environ.get("DEPLOYMENT_NAME", self.deployment.name)
        deployment_version = os.environ.get("DEPLOYMENT_VERSION")
        values = []
        # `start` is the offset of a slice within its request, so request_row
        # keeps counting from the request's first row.
        for index, row in enumerate(rows, start):
            entry = {name: row.get(name) for name in client_columns}
            for name in self.reserved_columns:
                if name == "deployment_name":
                    entry[name] = deployment_name
                elif name == "deployment_version":
                    entry[name] = (
                        int(deployment_version) if deployment_version else None
                    )
                elif name == "deployment_schema_id":
                    entry[name] = self.schema.schema_id
                elif name == "request_row":
                    entry[name] = index
            values.append(entry)
        return values

    @public
    def predict(self, inputs: Any, request_id: str | None = None) -> Any:
        """Serve one request: validate, look up, predict or return the vectors, log.

        Parameters:
            inputs: The request rows, as objects keyed by field name or arrays in schema order.
            request_id: Correlation id from the `x-request-id` header; generated when absent.

        Returns:
            The predictions list with a model, else `{"predictions": [...vectors...], "columns": [...]}`.
        """
        if not request_id:
            request_id = str(uuid.uuid4())
        try:
            rows = self.prepare_rows(inputs)
            vectors = self.fetch_feature_vectors(rows)
            if len(vectors) != len(rows):
                raise _http_error(
                    500,
                    "CONTRACT_VIOLATION",
                    f"The feature lookup returned {len(vectors)} vectors for "
                    f"{len(rows)} rows.",
                )
            output = self.model_predict(vectors)
            if self.model is None:
                columns = [str(c) for c in vectors.columns]
                self._check_output_columns(columns)
            else:
                count = _prediction_count(output)
                if count != len(rows):
                    raise _http_error(
                        500,
                        "CONTRACT_VIOLATION",
                        f"The model returned {count} predictions for {len(rows)} rows.",
                    )
            self.log(rows, vectors, output, request_id)
        except Exception as err:
            detail = getattr(err, "detail", None)
            if isinstance(detail, dict):
                detail.setdefault("request_id", request_id)
                _logger.error(
                    "Request %s failed with %s: %s",
                    request_id,
                    detail.get("code"),
                    detail.get("message"),
                    exc_info=err.__cause__ or err,
                )
            raise
        if self.model is None:
            return {"predictions": _frame_to_rows(vectors), "columns": columns}
        return output

    def _check_output_columns(self, columns: list[str]) -> None:
        published = self.schema.output.get("columns") if self.schema.output else None
        if not published:
            return
        expected = [c["name"] for c in published]
        if columns != expected:
            raise _http_error(
                500,
                "CONTRACT_VIOLATION",
                "The transformed feature vector has columns "
                f"{columns} but the schema publishes {expected}.",
            )

    # endregion


def _prediction_count(output: Any) -> int | None:
    """Rows in a model output: a list, an array, or a dict carrying `predictions`."""
    if isinstance(output, dict):
        output = output.get("predictions")
    if hasattr(output, "shape") and len(getattr(output, "shape", ())) > 0:
        return int(output.shape[0])
    try:
        return len(output)
    except TypeError:
        return None


def _is_null(value: Any) -> bool:
    """True for a missing scalar; a collection is a value, however empty or null its elements."""
    if value is None:
        return True
    if isinstance(value, (list, tuple, dict, set, str, bytes)):
        return False
    if isinstance(value, float) and math.isnan(value):
        return True
    if getattr(value, "ndim", 0):
        return False
    try:
        import pandas as pd

        return bool(pd.isna(value))
    except Exception:  # noqa: BLE001 - not a pandas scalar, or pandas missing
        return False


def _frame_to_rows(frame) -> list[list[Any]]:
    rows = []
    for record in frame.itertuples(index=False, name=None):
        rows.append([None if _is_null(v) else _encode_value(v) for v in record])
    return rows


def _family_of_any(type_: Any) -> str | None:
    """Type family for either a feature store offline type or a pandas dtype name."""
    if type_ is None:
        return None
    text = str(type_).lower()
    family = _family(text)
    if family is not None:
        return family
    for prefix, pandas_family in _PANDAS_FAMILIES.items():
        if text.startswith(prefix):
            return pandas_family
    return None
