# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.engine.execution_engine
ExecutionEngine = hopsworks.internal.platform.engine.execution_engine.ExecutionEngine
