# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.auth
ApiKeyAuth = hopsworks.internal.platform.client.auth.ApiKeyAuth
BearerAuth = hopsworks.internal.platform.client.auth.BearerAuth
OnlineStoreKeyAuth = hopsworks.internal.platform.client.auth.OnlineStoreKeyAuth
get_api_key = hopsworks.internal.platform.client.auth.get_api_key
