# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.client.istio.base
Client = hopsworks.internal.platform.client.istio.base.Client
