# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.decorators
HopsworksConnectionError = hopsworks.internal.platform.decorators.HopsworksConnectionError
NoHopsworksConnectionError = hopsworks.internal.platform.decorators.NoHopsworksConnectionError
TypeVar = hopsworks.internal.platform.decorators.TypeVar
_T = hopsworks.internal.platform.decorators._T
catch_not_found = hopsworks.internal.platform.decorators.catch_not_found
connected = hopsworks.internal.platform.decorators.connected
not_connected = hopsworks.internal.platform.decorators.not_connected
typechecked = hopsworks.internal.platform.decorators.typechecked
uses_confluent_kafka = hopsworks.internal.platform.decorators.uses_confluent_kafka
uses_great_expectations = hopsworks.internal.platform.decorators.uses_great_expectations
uses_polars = hopsworks.internal.platform.decorators.uses_polars
