# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.core.monitoring_window_config
MonitoringWindowConfig = hopsworks.internal.fs.core.monitoring_window_config.MonitoringWindowConfig
WindowConfigType = hopsworks.internal.fs.core.monitoring_window_config.WindowConfigType
