#
#   Copyright 2026 Hopsworks AB
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
"""Executable semantics of the point-in-time WINDOWED aggregation timeline plan.

The backend computes a windowed aggregate per training (spine) row with a
spine-marker timeline whose window frames are all CUMULATIVE (review PIT-P1:
Spark evaluates a finite RANGE frame near-quadratically on a dense entity, its
unbounded frame incrementally).
SUM/COUNT/AVG ride signed deltas with an expiry twin per source row at
ord + window + 1 microsecond; MIN/MAX use the exact two-bucket decomposition
(forward and backward cumulative extrema per window-sized bucket, merged
between the marker and a probe row at the window's lower bound).

The .sql resources here are byte-identical copies of the golden files the
backend test `TestConstructorControllerCollect` (hopsworks-ee,
src/test/resources/x2/) asserts against its generator output, and they are
EXECUTED verbatim on Spark and DuckDB against fixtures chosen to hit the
boundary math (review X2-R19).

Covered semantics, on both engines:
- partial expiry: rows older than (spine - window) do not leak;
- the lower bound is inclusive at exact microsecond precision (a fractional
  event 0.1 s inside or outside the bound flips membership);
- a spine long after the entity's last event reads an EMPTY window
  (COUNT 0, SUM/AVG/MIN/MAX NULL) — the delta sums cancel and the guards
  restore NULL;
- an entity with no source rows at all reads the same empty-window values;
- EXACT duplicate spine rows both survive (distinct ROW_NUMBER identity);
- NULL source values count for COUNT(*) but not for min/max/avg;
- a marker exactly on a bucket boundary and a probe at a negative epoch
  ordinal still merge the two bucket extrema to exactly [s - w, s].
"""

from __future__ import annotations

import pytest


RESOURCES = __file__.rsplit("/", 1)[0] + "/resources"

# fixtures for the GOLDEN generated statements (window = 3600 s, tables
# `fs1`.`labels_1` / `fs1`.`fg1_1` exactly as generated by the backend):
# entity 1 has events at 1000 s (amount 1), 2000 s (2), 4000 s (4), and
# 4600.5 s (8) — the fractional row exercises the microsecond bound
GOLDEN_SOURCE = [
    (1, 1000.0, 1.0),
    (1, 2000.0, 2.0),
    (1, 4000.0, 4.0),
    (1, 4600.5, 8.0),
]
# spine: inclusive lower bound (4600 - 3600 = 1000), one-second-later
# exclusion as an EXACT duplicate spine row pair (bag semantics), fractional
# bounds around the 4600.5 event, an idle spine, and an entity with no rows
GOLDEN_SPINE = [
    (1, 4600.0, 0.0),
    (1, 4601.0, 0.0),
    (1, 4601.0, 0.0),
    (1, 8200.4, 0.0),
    (1, 8200.6, 0.0),
    (1, 9999.0, 1.0),
    (2, 4600.0, 1.0),
]
# one output row per spine row: (pk, sec, is_fraud, amount_sum, count)
GOLDEN_EXPECTED = sorted(
    [
        # window [1000, 4600]: 4600.5 is outside, 1000 sits ON the bound
        (1, 4600.0, 0.0, 7.0, 3),
        # window [1001, 4601]: 1000 expired, 4600.5 inside
        (1, 4601.0, 0.0, 14.0, 3),
        (1, 4601.0, 0.0, 14.0, 3),
        # window [4600.4, 8200.4]: only the fractional 4600.5 event
        (1, 8200.4, 0.0, 8.0, 1),
        # window [4600.6, 8200.6]: 4600.5 < 4600.6 -> excluded
        (1, 8200.6, 0.0, None, 0),
        # window [6399, 9999]: nothing
        (1, 9999.0, 1.0, None, 0),
        # entity with no source rows at all
        (2, 4600.0, 1.0, None, 0),
    ],
    key=str,
)


# fixtures for the extremum golden ({amount: [min, max, avg]}, window 3600 s):
# a NULL amount at 6500 s is visible to COUNT-style guards but must never
# reach min/max/avg
EXTREMUM_SOURCE = [
    (1, 1000.0, 5.0),
    (1, 2000.0, 1.0),
    (1, 4000.0, 9.0),
    (1, 4600.5, 3.0),
    (1, 6500.0, None),
]
# spine: a plain window, an EXACT duplicate pair, a marker exactly ON a
# bucket boundary (7200 = 2 x 3600), a window whose probe ordinal is a
# NEGATIVE epoch (2000 - 3600), a mid-bucket window, an idle spine, and an
# entity with no rows
EXTREMUM_SPINE = [
    (1, 4600.0, 0.0),
    (1, 4600.0, 0.0),
    (1, 7200.0, 0.0),
    (1, 2000.0, 0.0),
    (1, 6600.0, 0.0),
    (1, 9999.0, 1.0),
    (2, 4600.0, 1.0),
]
# one output row per spine row: (pk, sec, is_fraud, min, max, avg)
EXTREMUM_EXPECTED = sorted(
    [
        # window [1000, 4600]: amounts 5, 1, 9
        (1, 4600.0, 0.0, 1.0, 9.0, 5.0),
        (1, 4600.0, 0.0, 1.0, 9.0, 5.0),
        # marker ON the bucket boundary; window [3600, 7200]: 9, 3, NULL
        (1, 7200.0, 0.0, 3.0, 9.0, 6.0),
        # probe at NEGATIVE epoch -1600 s; window [-1600, 2000]: 5, 1
        (1, 2000.0, 0.0, 1.0, 5.0, 3.0),
        # window [3000, 6600]: 9, 3, NULL
        (1, 6600.0, 0.0, 3.0, 9.0, 6.0),
        # empty window
        (1, 9999.0, 1.0, None, None, None),
        # entity with no source rows at all
        (2, 4600.0, 1.0, None, None, None),
    ],
    key=str,
)


def _spark_session(tmp_path, app_name):
    from pyspark.sql import SparkSession

    return (
        SparkSession.builder.master("local[2]")
        .appName(app_name)
        .config("spark.ui.enabled", "false")
        .config("spark.sql.warehouse.dir", str(tmp_path))
        .getOrCreate()
    )


def _spark_run_golden(spark, resource, source_rows, spine_rows):
    with open(f"{RESOURCES}/{resource}") as f:
        sql = f.read().strip()
    spark.sql("CREATE DATABASE IF NOT EXISTS fs1")
    spark.createDataFrame(source_rows, "pk long, sec double, amount double").selectExpr(
        "pk", "timestamp_seconds(sec) AS ts", "amount"
    ).write.mode("overwrite").saveAsTable("fs1.fg1_1")
    spark.createDataFrame(
        spine_rows, "pk long, sec double, is_fraud double"
    ).selectExpr("pk", "timestamp_seconds(sec) AS ts", "is_fraud").write.mode(
        "overwrite"
    ).saveAsTable("fs1.labels_1")
    return spark.sql(sql).collect()


def _duckdb_run_golden(resource, source_rows, spine_rows):
    duckdb = pytest.importorskip("duckdb")

    with open(f"{RESOURCES}/{resource}") as f:
        sql = f.read().strip()
    con = duckdb.connect()
    con.execute("CREATE SCHEMA fs1")
    con.execute("CREATE TABLE fs1.fg1_1 (pk BIGINT, ts TIMESTAMP, amount DOUBLE)")
    for pk, sec, amount in source_rows:
        con.execute(
            "INSERT INTO fs1.fg1_1 SELECT ?, to_timestamp(?), ?", [pk, sec, amount]
        )
    con.execute("CREATE TABLE fs1.labels_1 (pk BIGINT, ts TIMESTAMP, is_fraud DOUBLE)")
    for pk, sec, is_fraud in spine_rows:
        con.execute(
            "INSERT INTO fs1.labels_1 SELECT ?, to_timestamp(?), ?",
            [pk, sec, is_fraud],
        )
    return con.execute(sql).fetchall()


class TestPitWindowedTimelineGoldenSql:
    """Execute the backend-GENERATED sum/count statements verbatim."""

    def test_spark_generated_sql(self, tmp_path):
        pytest.importorskip("pyspark")
        spark = _spark_session(tmp_path, "pit-windowed-timeline-golden")
        try:
            rows = _spark_run_golden(
                spark, "pit_windowed_timeline_spark.sql", GOLDEN_SOURCE, GOLDEN_SPINE
            )
            got = sorted(
                [
                    (
                        r["pk"],
                        r["ts"].timestamp(),
                        r["is_fraud"],
                        r["amount_sum"],
                        r["count"],
                    )
                    for r in rows
                ],
                key=str,
            )
            assert got == GOLDEN_EXPECTED, got
        finally:
            spark.stop()

    def test_duckdb_generated_sql(self):
        rows = _duckdb_run_golden(
            "pit_windowed_timeline_duckdb.sql", GOLDEN_SOURCE, GOLDEN_SPINE
        )
        got = sorted(
            [
                (pk, ts.timestamp(), is_fraud, amount_sum, cnt)
                for pk, ts, is_fraud, amount_sum, cnt in rows
            ],
            key=str,
        )
        assert got == GOLDEN_EXPECTED, got


class TestPitWindowedExtremumGoldenSql:
    """Execute the backend-GENERATED min/max/avg statements verbatim.

    These pin the two-bucket decomposition: forward and backward cumulative
    extrema per (entity, bucket) merged between the marker and its probe row,
    including a marker exactly on a bucket boundary and a probe at a negative
    epoch ordinal.
    """

    def test_spark_generated_sql(self, tmp_path):
        pytest.importorskip("pyspark")
        spark = _spark_session(tmp_path, "pit-windowed-extremum-golden")
        try:
            rows = _spark_run_golden(
                spark,
                "pit_windowed_extremum_spark.sql",
                EXTREMUM_SOURCE,
                EXTREMUM_SPINE,
            )
            got = sorted(
                [
                    (
                        r["pk"],
                        r["ts"].timestamp(),
                        r["is_fraud"],
                        r["amount_min"],
                        r["amount_max"],
                        r["amount_avg"],
                    )
                    for r in rows
                ],
                key=str,
            )
            assert got == EXTREMUM_EXPECTED, got
        finally:
            spark.stop()

    def test_duckdb_generated_sql(self):
        rows = _duckdb_run_golden(
            "pit_windowed_extremum_duckdb.sql", EXTREMUM_SOURCE, EXTREMUM_SPINE
        )
        got = sorted(
            [
                (pk, ts.timestamp(), is_fraud, amount_min, amount_max, amount_avg)
                for pk, ts, is_fraud, amount_min, amount_max, amount_avg in rows
            ],
            key=str,
        )
        assert got == EXTREMUM_EXPECTED, got
