# This file is generated by hopsworks-apigen.
# Do not edit it manually!
# It is managed by hopsworks-apigen and is subject to periodical deletion.
import hopsworks_common.core.sink_job_configuration


FeatureColumnMapping = hopsworks_common.core.sink_job_configuration.FeatureColumnMapping
LoadingConfig = hopsworks_common.core.sink_job_configuration.LoadingConfig
SinkJobConfiguration = hopsworks_common.core.sink_job_configuration.SinkJobConfiguration
