name: Basic e2e tests

on: pull_request

jobs:
    e2e_quick:
        runs-on: ghrunner-hopsworks-api-vatj
        env:
            VENV_PATH: /home/runner/envs/.venv
        steps:
            - name: Checkout hopsworks-api SDK
              uses: actions/checkout@v4
              with:
                  path: hopsworks-api
                  ref: ${{ github.event.pull_request.head.sha }}
            
            - name: Checkout loadtest project
              uses: actions/checkout@v4
              with:
                  repository: 'vatj/loadtest'
                  ref: 'draft-e2e-script-staging'
                  token: ${{ secrets.PAT_LOADTEST }}
                  path: loadtest
            
            - name: Install latest client SDK
              run: |
                echo $VENV_PATH
                source $VENV_PATH/bin/activate
                pip uninstall -y hopsworks
                pip install ${{github.workspace}}/hopsworks-api/python
            
            - name: List dependencies
              run: |
                source $VENV_PATH/bin/activate
                pip freeze

            - name: Runs only e2e tests suite
              env:
                MARKER: 'python_quick_e2e'
              run: |
                cd ${{github.workspace}}/loadtest/tests
                ./run_e2e_on_runner.sh $MARKER