name: Basic e2e tests

on: pull_request

jobs:
    e2e_quick:
        runs-on: ghrunner-hopsworks-api-vatj
        steps:
            - name: Checkout hopsworks-api SDK
              uses: actions/checkout@v4
              with:
                path: ${{ github.workspace }}
            
            - name: Checkout loadtest project
              uses: actions/checkout@v4
              with:
                  repository: 'vatj/loadtest'
                  ref: 'draft-e2e-script-staging'
                  token: ${{ secrets.PAT_LOADTEST }}
                  path: ${{github.workspace}}
            
            - name: Install python dependencies and sdk
              run: | 
                pipx install -e 'hopsworks @ ${{ github.workspace }}/hopsworks-api/python'

            - name: Runs only e2e tests suite
              env:
                MARKER: 'python_quick_e2e'
              run: |
                cd ${{github.workspace}}/loadtest/tests
                ./run_e2e_on_runner.sh $MARKER