name: Basic e2e tests

on: pull_request

jobs:
    e2e_quick:
        runs-on: ghrunner-hopsworks-api-vatj
        steps:
            - run: |
                echo "Workspace is ${{ github.workspace }}"
                pwd
                ls -lha

            - name: Checkout hopsworks-api SDK
              uses: actions/checkout@v4
            
            - name: Checkout loadtest project
              uses: actions/checkout@v4
              with:
                  repository: 'vatj/loadtest'
                  ref: 'draft-e2e-script-staging'
                  token: ${{ secrets.PAT_LOADTEST }}
            
            - name: Install python dependencies and sdk
              run: | 
                sleep 120
                pipx install ${{github.workspace}}/hopsworks-api/python

            - name: Runs only e2e tests suite
              env:
                MARKER: 'python_quick_e2e'
              run: |
                cd ${{github.workspace}}/loadtest/tests
                ./run_e2e_on_runner.sh $MARKER