name: End-to-End Workflow Tests

on: pull_request

jobs:
    e2e_workflows:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get the short sha
              id: short_sha
              run: |
                export SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
                echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
                echo "Hello"

            - name: Calling Loadtest Workflow
              uses: logicalclocks/loadtest/.github/workflows/e2e_small.yaml@main
              with:
                hopsworks_domain: 'stagingmain.devnet.hops.works'
                hopsworks_api_branch: ${{ github.event.pull_request.head.ref}}
                loadtest_branch: ${{ github.event.pull_request.head.ref || 'main'}}
                short_sha: ${{ env.SHORT_SHA }}

            
                

            

