# ruff: noqa
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.kafka_api
KafkaApi = hopsworks.internal.platform.core.kafka_api.KafkaApi
