# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.platform.core.tags_api
TagsApi = hopsworks.internal.platform.core.tags_api.TagsApi
