# ruff: noqa
# fmt: off
# This file is generated by aliases.py. Do not edit it manually!
import hopsworks.internal.aliases
import hopsworks.internal.fs.transformation_statistics
FeatureTransformationStatistics = hopsworks.internal.fs.transformation_statistics.FeatureTransformationStatistics
TransformationStatistics = hopsworks.internal.fs.transformation_statistics.TransformationStatistics
